#3503 Add xslt.features support
apache/camel-quarkus pull request #3526
Opened 2022-02-06 11:06 UTC by DenisIstomin

Related to #3503

2022-02-07 15:48 UTC, ppalaga requested changes
Thanks, @DenisIstomin this looks quite good! 

Except for the inline suggestions, could you please add some test coverage to the test module under `integration-tests/xml`? Ideally a new XSLT file. If the functions implementations really have to be in a separate jar file, the you can create a new module under `/integration-tests-support`.

2022-02-07 15:48 UTC, ppalaga commented on integration-tests/xml/src/main/resources/application.properties
> +quarkus.camel.xslt.features."http\://javax.xml.XMLConstants/feature/secure-processing" = true
This change is not necessary because `true` is the default, no?

2022-02-08 11:00 UTC, DenisIstomin commented on extensions/xslt/runtime/src/main/java/org/apache/camel/quarkus/component/xslt/CamelXsltRecorder.java
> +                    LOGGER.warn("Unsupported TransformerFactory feature {}", entry.getKey());
Thanks, fixed

2022-02-08 11:03 UTC, DenisIstomin commented
Thanks @ppalaga, added an integration test for the extension functions.

2022-02-08 11:24 UTC, ppalaga commented
Great work, thanks @DenisIstomin !

I am checking locally, whether I can make loading the functions from the current project work. 
FWIW, it works in native mode because the classloader there is flat.

I have sent https://github.com/apache/camel-quarkus/pull/3533 to unblock building this and other PRs

2022-02-08 12:05 UTC, ppalaga commented
> I am checking locally, whether I can make loading the functions from the current project work.
> FWIW, it works in native mode because the classloader there is flat.

I think this is caused by the fact that TransformerFactory class is resolved using a wrong class loader around here in Camel https://github.com/apache/camel/blob/camel-3.15.0/components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltEndpoint.java#L372

I'd say this PR is good to go like this with the known limitation and I'll file a followup issue for the class loading problem.

2022-02-08 15:21 UTC, ppalaga commented
The CI build should work now. Could you please squash your two commits, rebase on top of the recent master and force-push? - That should re-trigger the CI for this PR.

2022-02-08 19:46 UTC, ppalaga approved these changes
Thanks again, @DenisIstomin !

2022-02-08 19:47 UTC, merged